### ISSUE TITLE
Implement tagging

### ISSUE THREAD

**Issue by faisalsayed10** [faisalsayed10/firefiles#44]
_For CodeDay Labs_

Object Storage buckets, like S3, allow users to add tags to the objects. This enables the users to better manage their files and filter them when needed.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/tagging-managing.html

Your task is to implement a tagging system for files through which the user will directly interact with these APIs and add / remove / edit tags.

**Comment by alisonfung** [comment]
I am working on this with @Cao1224 and @nehapinni.

**Comment by faisalsayed10** [comment]
Awesome

**Comment by alisonfung** [comment]
After investigating the issue with my team, we have a few questions.

Since tagging is an S3 feature, does the issue intend for tags to only be available if S3 is the provider? 
If this is the case, then we will need to enable/disable the tags UI depending on the current provider, correct?
Also to note is that [Backblaze currently does not support object tagging through their S3 compatible API](https://www.backblaze.com/docs/cloud-storage-s3-compatible-api#get-object-tagging). 

Please let us know any advice or guidance you have. Thank you!

**Comment by faisalsayed10** [comment]
Oh, I see. yeah, we can make it such that if tags are not supported, we disable it and show a message in the UI that they aren't supported. For the rest of them, we can add the tags. Also, please make sure that it is recreate-able for other buckets (like how `addFile`, `deleteFile` functions are written, we could have common functions like  `listTags`, `removeTags`, `updateTags` etc. that can we rewritten for different buckets)

Also for firebase, we could use file metadata to store tags - https://firebase.google.com/docs/storage/web/file-metadata

I hope this answers all your questions, lmk if there's anything else. Thanks!

**Comment by faisalsayed10** [comment]
Merged by #63
